### ISSUE TITLE
Create User Interface

### ISSUE THREAD

**Issue by GracieLovelight** [PlayerZeroStudios/The-Gateway#3]
## Create a User Interface:

- [ ] Fork the code from the [Simple Multi-Launcher](https://github.com/Arbitrium-Studios/Simple-Multi-Launcher) to this repository
- [ ] Convert the code to Python.
- [ ] Create the UI using a combination of the HTML, CSS, with latest version of Python, and any other necessary assets
- [ ] The UI should be easy and intuitive to use.
- [ ] It should come with a Dark Mode and a Light Mode
- [ ] It should detect your system's default theme and use that.
- [ ] The code should be future-proofed so that anyone can make their own custom theme in CSS
- [ ] There should be a [Landing Page](https://github.com/Arbitrium-Studios/The-Gateway-Launcher/issues/5)
- [ ] There should be a [Library Page](https://github.com/Arbitrium-Studios/The-Gateway-Launcher/issues/6)
- [ ] There should be a [Settings Menu](https://github.com/Arbitrium-Studios/The-Gateway-Launcher/issues/4)

### More will be added later on...
